server:
  port: 8082
  external:
    url: http://localhost:8080/api
    access-token : ${server.external.url}/auth/authenticate
    refresh-token : ${server.external.url}/auth/refresh
    user : ${server.external.url}/user
    student : ${server.external.url}/student
    admin : ${server.external.url}/admin
    group : ${server.external.url}/groups

spring:
  datasource:
    url: jdbc:h2:file:./data/db
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update


